name: Update GitHub Wiki

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  update-wiki:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Clone Wiki Repository
      run: |
        git clone https://github.com/${{ github.repository }}.wiki.git wiki
        cd wiki
        git checkout main

    - name: Update Wiki
      run: |
        cp -r path/to/your/wiki/content/* wiki/  # Copy wiki content
        cd wiki
        git add .
        git commit -m "Update wiki content"
        git push

    - name: Cleanup
      run: |
        rm -rf wiki
